name: Lint

on: 
    pull_request:
    # The branches below must be a subset of the branches above
        branches: [ main ]
    

jobs:
    checks:
        name: basic_assess
        runs-on: ubuntu-latest
        steps:
        - name: Lint content files
          uses: articulate/actions-markdownlint@v1
          with:
            config: markdownlint-config.json
            files: 'content/**/*.md'